.build_docker_harbor_registry:
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^main?|^develop?|^qa?|^test?|^demo?/'
      variables:
        BUILD_VERSION: "$CI_COMMIT_REF_SLUG"
        PUSH: "true"
      # when: manual
    - if: $CI_COMMIT_TAG
      variables:
        BUILD_VERSION: "$CI_COMMIT_TAG"
        PUSH: "true"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        BUILD_VERSION: "$CI_COMMIT_REF_SLUG"
        PUSH: "false"
    - if: $CI_COMMIT_BRANCH
      variables:
        BUILD_VERSION: "$CI_COMMIT_REF_SLUG"
        PUSH: "false"
      # when: manual
  image:
    name: docker:24.0.3
    # entrypoint: [ "" ]
  variables:
    DOCKER_DIR: "./"
    DOCKERFILE: "./Dockerfile"
    APP: ""
    DOCKER_BUILDKIT: 1
  stage: build
  before_script:
    - docker login ${HARBOR_PROD} -u ${HARBOR_USER} -p ${HARBOR_TOKEN}
  script:
    - env
    - export datetag=$(date +%Y-%m-%d-%H-%M-%S)
    # - cd $DOCKER_DIR
    - docker login docker.io -u devopspredicto -p ${DEVOPSPREDICTO}
    - docker build
      --platform "linux/amd64"
      --file "${DOCKERFILE}"
      --tag ${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION
      --tag ${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION-date-$datetag
      --build-arg BUILD_VERSION=$BUILD_VERSION
      "${DOCKER_DIR}"
    - env
    - if [ "$PUSH" == "true" ]; then echo "pushing images"; else exit 0; fi
    - echo "docker push ${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION"
    - docker push "${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION" || true
    - echo "docker push ${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION-date-$datetag"
    - docker push "${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION-date-$datetag"
  # after_script:
  #   - docker image rm -f "${HARBOR_PROD}/${HARBOR_PROJECT}$CI_PROJECT_NAME:$BUILD_VERSION-sha-$CI_COMMIT_SHA" || true
  tags:
    - dind

